language: python
os:
  - linux
rvm:
  - 3.5
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran
before_install:
  - export PATH=./lammps_interface/bin:$PATH
install:
  - pip install .
script:
  - cd tests
  - python test.py
